server:
  port: 8084

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id : USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**,/staffs/**
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

